version: '3.7'

services:
  # Development container. Runs in debug mode and live-reloading on every source file update.
  development-backend:
    hostname: backend-api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    volumes:
      - ./:/app
    ports:
      - "8081:8081"

  redis:
    image: redis/redis-stack:edge
    volumes:
      - ./redis:/setup
    ports:
      - '6379:6379'
    
  redis-setup:
    image: redis/redis-stack:edge
    restart: "no"
    depends_on:
      - redis
    volumes:
      - ./redis:/setup
    entrypoint: bash -c './setup/setup.sh redis 6379'