version: '3.7'

services:
  # Development container. Runs in debug mode and live-reloading on every source file update.
  development-backend:
    hostname: backend-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8081:8081"
